<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Manifest\EasyTierParameter.json" />
      <EmbeddedResource Include="Manifest\EasyTierParameter.json" />
      <None Remove="Manifest\PublicServerList.json" />
      <EmbeddedResource Include="Manifest\PublicServerList.json" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Tomlyn" Version="0.20.0" />
    </ItemGroup>

</Project>
